[package]
name = "dma-node"
version = "0.0.1"
authors = ["thalesfragoso <thales.fragosoz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-array = "0.13"
as-slice = "0.1"
